### ISSUE TITLE
2013 plate requests

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [rjindael/ca-dmv-bot#3]
In case you ever run low on plates (and still want to keep going): https://www.muckrock.com/foi/california-52/rejected-personalized-aka-vanity-license-plates-in-2013-department-of-motor-vehicles-11655/files/

~300 excel spreadsheets, needs the same work described in the readme of [veltman/ca-license-plates](https://github.com/veltman/ca-license-plates) (found a full name just glancing through)

**Comment by rjindael** [comment]
By my napkin math, the data from [@veltman/ca-license-plates](https://github.com/veltman/ca-license-plates) should last the bot for 2-3 years given its current post rate. I believe that if I would compile additional records, I'd rather it be an entirely separate project with an emphasis on archival as opposed to it being used in a Twitter gimmick account.

Here are some other MuckRock FoIA/L requests that I've been forwarded since the bot launched;
- **Connecticut:** https://www.muckrock.com/foi/connecticut-53/connecticut-denied-personalized-license-plates-125598/ (correspondence dated March 1, 2022)
- **New Jersey:** https://www.muckrock.com/foi/new-jersey-229/rejected-personalized-aka-vanity-license-plates-in-2013-motor-vehicle-commission-11649/ (correspondence dated May 7, 2014)
- **Montana:** https://www.muckrock.com/foi/montana-157/rejected-vanity-plates-in-montana-11681/ (correspondence dated May 9, 2014)

These are the ones I currently have on hand. From a quick search, there's a [lot more](https://www.muckrock.com/search/?q=vanity+plate) to be discovered.

I'm closing this for now since I don't think it's worth adding any new records at the moment. If I get the time (and if anybody would care), I'll probably start the aforementioned project and compile these records. Thank you for submitting this issue, though; I haven't seen these records until now.
